Fix ssh key authentication
Prevent errors such as:

  IOError: [Errno 2] No such file or directory: 'c'

because key_file is a string instead of being an array.

Closes #152

Signed-off-by: Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>