fix: update regex for newer junos prompt
[ error ]
    Exception in thread Thread-1:
    Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/protocol.py", line 769, in _app_authenticate
    index, match = self._waitfor(prompt_list)
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/protocol.py", line 986, in _waitfor
    result = self._domatch(re_list, False)
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/ssh2.py", line 422, in _domatch
    if not self._fill_buffer():
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/ssh2.py", line 393, in _fill_buffer
    raise TimeoutException(error)
    Exscript.protocols.exception.TimeoutException: Timeout while waiting for response from device

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
    File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
    File "", line 74, in 
    conn.login(account)
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/protocol.py", line 675, in login
    self.authenticate(account, flush=False)
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/protocol.py", line 701, in authenticate
    self.app_authenticate(app_account, flush=flush)
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/protocol.py", line 870, in app_authenticate
    self._app_authenticate(account, password, flush, bailout)
    File "/usr/local/lib/python3.5/dist-packages/Exscript/protocols/protocol.py", line 774, in _app_authenticate
    raise TimeoutException(msg)
    Exscript.protocols.exception.TimeoutException: Buffer: ''

[ cause ]
The shell prompt has changed in newer JunOS versions

[ prompt ]
14.1R7.4: root@dev1%
18.4R3.3: root@dev1:~ #

[ fix ]
Add support for new prompt